---
- name: "Enable and start SSH"
  register: install_ssh__service_status
  changed_when: install_ssh__service_status.state != "started"
  ansible.builtin.service:
    name: "ssh"
    state: "started"
    enabled: yes

- name: "Restart SSH"
  register: install_ssh__service_status
  changed_when: install_ssh__service_status.state != "restarted"
  ansible.builtin.service:
    name: "ssh"
    state: "restarted"
    daemon_reload: true
