---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.install_ssh"
      tags:
        - "labocbz.install_ssh"
      vars:
        install_ssh__port: "{{ inv_install_ssh__port }}"
        install_ssh__administration_name: "{{ inv_install_ssh__administration_name }}"
      ansible.builtin.include_role:
        name: "labocbz.install_ssh"
