---
# Don't forget to keep this file updated
# molecule/<scenario>/verify.yml
- name: "Verify"
  hosts: "cicd-ubuntu-22"
  gather_facts: false
  tasks:

    - name: "Get SSH service current state"
      register: install_ssh__service_status
      failed_when: not install_ssh__service_status.status.ActiveState == 'active'
      ansible.builtin.systemd:
        name: "sshd"

    - name: "Check SSH connectivity"
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ inv_install_ssh__port }}"
        timeout: 120

    - name: "Check SSH banners and conf"
      loop:
        - "/etc/issue"
        - "/etc/issue.net"
        - "/etc/ssh/sshd_config"
      loop_control:
        loop_var: banner_path
      register: file_check
      failed_when: not file_check.stat.exists
      ansible.builtin.stat:
        path: "{{ banner_path }}"